### ISSUE TITLE
Proposal: TypedBus

### ISSUE THREAD

**Issue by pulsejet** [nextcloud-libraries/nextcloud-event-bus#708]
Memories currently uses an extension of the event bus to get static typing on event names and callbacks; see:

https://github.com/pulsejet/memories/blob/f5627da48868988615f17e5a5b66215cabf37323/src/services/utils/event-bus.ts#L5

Would you be interested in such an implementation to be merged upstream?

@skjnldsv @susnux

**Comment by skjnldsv** [comment]
Aaaahh! I always wanted to have something like this yes! :heart_eyes: 
So, the only issue I have with that, is keeping it in sync. Would be awesome if we had a tooling parsing events on various repos and extracting the data automatically (maybe if there is a comment above or something)

But to keep it simple, we could also add typing to our bus, and that would work too!

In any case, I'm definitely interested, I think it make sense to have a publicly available list of "official" events names and their data

**Comment by pulsejet** [comment]
Awesome! I'll make a generic PR when I get back home then (probably mid jan).

Perhaps it might make sense to keep this repo completely generic (i.e. the typed bus initializer takes a template argument) and then keep the built-in events can be defined in `@nextcloud/typings` (a "default" bus that uses this types can still be exported from this package)

Either way, the generic bus will be needed for third party apps which use their own events.
